manifest = "ad811491b6235f4af26b5b1dd2538b44d58da2443f1bb8fc3c24a6fdebe50763"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_index"
target = "//:type-index"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "branch=master" ]
revision = "ddd9a887f1f0253ded4455d455b3c54228067b74"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "branch=master" ]
revision = "562999d5a72c5f6641cd09c7a48715bbc6564c95"
