manifest = "ad811491b6235f4af26b5b1dd2538b44d58da2443f1bb8fc3c24a6fdebe50763"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_index"
target = "//:type-index"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "branch=master" ]
revision = "9446eb516e717ae9c80bc89768a8d1160bcf6887"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "branch=master" ]
revision = "20fb7a55b42537123e4c0e617b94145564f05e59"
